#![crate_id = "swresample0"]
#![license = "MIT"]
#![crate_type = "dylib"]
/* automatically generated by rust-bindgen */
extern crate libc;
extern crate avutil52;
use libc::{c_void,c_uint,c_int,uint8_t,int64_t,c_double,c_schar};

pub type __int128_t = c_void;
pub type __uint128_t = c_void;
pub type __builtin_va_list = [__va_list_tag, ..1u];
pub type Enum_SwrDitherType = c_uint;
pub static SWR_DITHER_NONE: c_uint = 0;
pub static SWR_DITHER_RECTANGULAR: c_uint = 1;
pub static SWR_DITHER_TRIANGULAR: c_uint = 2;
pub static SWR_DITHER_TRIANGULAR_HIGHPASS: c_uint = 3;
pub static SWR_DITHER_NS: c_uint = 64;
pub static SWR_DITHER_NS_LIPSHITZ: c_uint = 65;
pub static SWR_DITHER_NS_F_WEIGHTED: c_uint = 66;
pub static SWR_DITHER_NS_MODIFIED_E_WEIGHTED: c_uint = 67;
pub static SWR_DITHER_NS_IMPROVED_E_WEIGHTED: c_uint = 68;
pub static SWR_DITHER_NS_SHIBATA: c_uint = 69;
pub static SWR_DITHER_NS_LOW_SHIBATA: c_uint = 70;
pub static SWR_DITHER_NS_HIGH_SHIBATA: c_uint = 71;
pub static SWR_DITHER_NB: c_uint = 72;
pub type Enum_SwrEngine = c_uint;
pub static SWR_ENGINE_SWR: c_uint = 0;
pub static SWR_ENGINE_SOXR: c_uint = 1;
pub static SWR_ENGINE_NB: c_uint = 2;
pub type Enum_SwrFilterType = c_uint;
pub static SWR_FILTER_TYPE_CUBIC: c_uint = 0;
pub static SWR_FILTER_TYPE_BLACKMAN_NUTTALL: c_uint = 1;
pub static SWR_FILTER_TYPE_KAISER: c_uint = 2;
pub type Struct_SwrContext = c_void;
pub type SwrContext = Struct_SwrContext;
pub type __va_list_tag = Struct___va_list_tag;
pub struct Struct___va_list_tag {
    pub gp_offset: c_uint,
    pub fp_offset: c_uint,
    pub overflow_arg_area: *mut c_void,
    pub reg_save_area: *mut c_void,
}
#[link(name = "swresample")]
extern "C" {
    pub fn swr_get_class() -> *avutil52::AVClass;
    pub fn swr_alloc() -> *mut Struct_SwrContext;
    pub fn swr_init(s: *mut Struct_SwrContext) -> c_int;
    pub fn swr_is_initialized(s: *mut Struct_SwrContext) -> c_int;
    pub fn swr_alloc_set_opts(s: *mut Struct_SwrContext,
                              out_ch_layout: int64_t,
                              out_sample_fmt: avutil52::Enum_AVSampleFormat,
                              out_sample_rate: c_int, in_ch_layout: int64_t,
                              in_sample_fmt: avutil52::Enum_AVSampleFormat,
                              in_sample_rate: c_int, log_offset: c_int,
                              log_ctx: *mut c_void) -> *mut Struct_SwrContext;
    pub fn swr_free(s: *mut *mut Struct_SwrContext);
    pub fn swr_convert(s: *mut Struct_SwrContext, out: *mut *mut uint8_t,
                       out_count: c_int, _in: *mut *uint8_t, in_count: c_int)
     -> c_int;
    pub fn swr_next_pts(s: *mut Struct_SwrContext, pts: int64_t) -> int64_t;
    pub fn swr_set_compensation(s: *mut Struct_SwrContext,
                                sample_delta: c_int,
                                compensation_distance: c_int) -> c_int;
    pub fn swr_set_channel_mapping(s: *mut Struct_SwrContext,
                                   channel_map: *c_int) -> c_int;
    pub fn swr_set_matrix(s: *mut Struct_SwrContext, matrix: *c_double,
                          stride: c_int) -> c_int;
    pub fn swr_drop_output(s: *mut Struct_SwrContext, count: c_int) -> c_int;
    pub fn swr_inject_silence(s: *mut Struct_SwrContext, count: c_int) ->
     c_int;
    pub fn swr_get_delay(s: *mut Struct_SwrContext, base: int64_t) -> int64_t;
    pub fn swresample_version() -> c_uint;
    pub fn swresample_configuration() -> *c_schar;
    pub fn swresample_license() -> *c_schar;
}

pub fn version() -> uint{
    unsafe {
        swresample_version() as uint
    }
}
pub fn license() -> ~str {
    unsafe {
        std::str::raw::from_c_str(swresample_license())
    }
}
