#[link(name = "avdevice", vers = "54.3.103")];
#[license = "MIT"];
#[crate_type = "lib"];
/* automatically generated by rust-bindgen */
use std::libc::{c_void,c_uint,c_schar};
mod dummy {
    #[link_args = "-lavdevice"]
    extern {}
}
pub type __int128_t = c_void;
pub type __uint128_t = c_void;
pub type __builtin_va_list = [__va_list_tag, ..1u];
pub type __va_list_tag = Struct___va_list_tag;
pub struct Struct___va_list_tag {
    gp_offset: c_uint,
    fp_offset: c_uint,
    overflow_arg_area: *mut c_void,
    reg_save_area: *mut c_void,
}
externfn!(fn avdevice_version() -> c_uint)
externfn!(fn avdevice_configuration() -> *c_schar)
externfn!(fn avdevice_license() -> *c_schar)
externfn!(fn avdevice_register_all())
